### ISSUE TITLE
Dependencias faltando na RN 0.57.1

### ISSUE THREAD

**Issue by TiagoHA** [rodrigooler/bus99#3]
yarn add --dev @babel/core  @babel/runtime

**Comment by rodrigooler** [comment]
@TiagoHA tentei instalar o @babel/core e o @babel/runtime mas não resolveu o problema, alguma ideia?

**Comment by TiagoHA** [comment]
Corrigiram na 57.3

**Comment by rodrigooler** [comment]
@TiagoHA boa vou atualizar depois.
